#############################################################################
# Makefile for building: easygraph
# Generated by qmake (2.01a) (Qt 4.4.0) on: Sat Jun 28 16:56:41 2008
# Project:  easygraph.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile easygraph.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.4.0/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-4.4.0/include/QtOpenGL -I/usr/local/Trolltech/Qt-4.4.0/include/QtOpenGL -I/usr/local/Trolltech/Qt-4.4.0/include -I. -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.4.0/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.4.0/lib -L/usr/X11R6/lib -lQtOpenGL -L/usr/local/Trolltech/Qt-4.4.0/lib -L/usr/X11R6/lib -pthread -pthread -pthread -pthread -pthread -pthread -lQtGui -lpng -lSM -lICE -pthread -pthread -lXi -lXrender -lXrandr -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lGLU -lGL -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ConstantsModel.cpp \
		Graphing.cpp \
		GraphingHelper.cpp \
		GraphWidget.cpp \
		main.cpp \
		Point.cpp \
		ReversePolishNotationCalculation.cpp \
		ShuntingYardAlgorithm.cpp moc_Graphing.cpp \
		moc_GraphWidget.cpp
OBJECTS       = ConstantsModel.o \
		Graphing.o \
		GraphingHelper.o \
		GraphWidget.o \
		main.o \
		Point.o \
		ReversePolishNotationCalculation.o \
		ShuntingYardAlgorithm.o \
		moc_Graphing.o \
		moc_GraphWidget.o
DIST          = /usr/local/Trolltech/Qt-4.4.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf \
		easygraph.pro
QMAKE_TARGET  = easygraph
DESTDIR       = 
TARGET        = easygraph

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_Graphing.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: easygraph.pro  /usr/local/Trolltech/Qt-4.4.0/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.4.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtOpenGL.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile easygraph.pro
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/opengl.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtOpenGL.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile easygraph.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/easygraph1.0.0 || $(MKDIR) .tmp/easygraph1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/easygraph1.0.0/ && $(COPY_FILE) --parents ConstantsModel.h Graphing.h GraphingHelper.h GraphWidget.h Point.h ReversePolishNotationCalculation.h ShuntingYardAlgorithm.h .tmp/easygraph1.0.0/ && $(COPY_FILE) --parents ConstantsModel.cpp Graphing.cpp GraphingHelper.cpp GraphWidget.cpp main.cpp Point.cpp ReversePolishNotationCalculation.cpp ShuntingYardAlgorithm.cpp .tmp/easygraph1.0.0/ && $(COPY_FILE) --parents Graphing.ui .tmp/easygraph1.0.0/ && (cd `dirname .tmp/easygraph1.0.0` && $(TAR) easygraph1.0.0.tar easygraph1.0.0 && $(COMPRESS) easygraph1.0.0.tar) && $(MOVE) `dirname .tmp/easygraph1.0.0`/easygraph1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/easygraph1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Graphing.cpp moc_GraphWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Graphing.cpp moc_GraphWidget.cpp
moc_Graphing.cpp: ui_Graphing.h \
		GraphWidget.h \
		Point.h \
		GraphingHelper.h \
		ConstantsModel.h \
		Graphing.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) Graphing.h -o moc_Graphing.cpp

moc_GraphWidget.cpp: Point.h \
		GraphingHelper.h \
		GraphWidget.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) GraphWidget.h -o moc_GraphWidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_Graphing.h
compiler_uic_clean:
	-$(DEL_FILE) ui_Graphing.h
ui_Graphing.h: Graphing.ui \
		GraphWidget.h \
		Point.h \
		GraphingHelper.h
	/usr/local/Trolltech/Qt-4.4.0/bin/uic Graphing.ui -o ui_Graphing.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

ConstantsModel.o: ConstantsModel.cpp ConstantsModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConstantsModel.o ConstantsModel.cpp

Graphing.o: Graphing.cpp Graphing.h \
		ui_Graphing.h \
		GraphWidget.h \
		Point.h \
		GraphingHelper.h \
		ConstantsModel.h \
		ShuntingYardAlgorithm.h \
		ReversePolishNotationCalculation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Graphing.o Graphing.cpp

GraphingHelper.o: GraphingHelper.cpp GraphingHelper.h \
		Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GraphingHelper.o GraphingHelper.cpp

GraphWidget.o: GraphWidget.cpp GraphWidget.h \
		Point.h \
		GraphingHelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GraphWidget.o GraphWidget.cpp

main.o: main.cpp ShuntingYardAlgorithm.h \
		ConstantsModel.h \
		Graphing.h \
		ui_Graphing.h \
		GraphWidget.h \
		Point.h \
		GraphingHelper.h \
		ReversePolishNotationCalculation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Point.o: Point.cpp Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Point.o Point.cpp

ReversePolishNotationCalculation.o: ReversePolishNotationCalculation.cpp ReversePolishNotationCalculation.h \
		ConstantsModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ReversePolishNotationCalculation.o ReversePolishNotationCalculation.cpp

ShuntingYardAlgorithm.o: ShuntingYardAlgorithm.cpp ShuntingYardAlgorithm.h \
		ConstantsModel.h \
		ReversePolishNotationCalculation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ShuntingYardAlgorithm.o ShuntingYardAlgorithm.cpp

moc_Graphing.o: moc_Graphing.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Graphing.o moc_Graphing.cpp

moc_GraphWidget.o: moc_GraphWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GraphWidget.o moc_GraphWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

